# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 500)
        MainWindow.setMinimumSize(QtCore.QSize(400, 500))
        MainWindow.setMaximumSize(QtCore.QSize(400, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../texture/icontitle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: \'#121212\';\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(290, 480, 111, 16))
        self.label.setMaximumSize(QtCore.QSize(16777212, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background:none;")
        self.label.setObjectName("label")
        self.btn_play = QtWidgets.QPushButton(self.centralwidget)
        self.btn_play.setGeometry(QtCore.QRect(150, 330, 81, 81))
        self.btn_play.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_play.setStyleSheet("QPushButton {\n"
"\n"
"background: none;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.btn_play.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("texture/icon_play1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_play.setIcon(icon1)
        self.btn_play.setIconSize(QtCore.QSize(90, 90))
        self.btn_play.setFlat(True)
        self.btn_play.setObjectName("btn_play")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 430, 231, 41))
        self.label_2.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 12pt \"Segoe Fluent Icons\";\n"
"background: none;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 410, 371, 41))
        self.label_3.setStyleSheet("color: rgb(255, 0, 0);\n"
"background: none;\n"
"font: 12pt \"Segoe Fluent Icons\";")
        self.label_3.setObjectName("label_3")
        self.btn_settings = QtWidgets.QPushButton(self.centralwidget)
        self.btn_settings.setGeometry(QtCore.QRect(360, 10, 31, 31))
        font = QtGui.QFont()
        font.setKerning(True)
        self.btn_settings.setFont(font)
        self.btn_settings.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_settings.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_settings.setStyleSheet("QPushButton{\n"
"border: 1px solid \'black\';\n"
"border-radius:15px;\n"
"background: none;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"border-color: rgb(255, 255, 255);\n"
"}")
        self.btn_settings.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("texture/icon_settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_settings.setIcon(icon2)
        self.btn_settings.setIconSize(QtCore.QSize(30, 30))
        self.btn_settings.setCheckable(False)
        self.btn_settings.setFlat(True)
        self.btn_settings.setObjectName("btn_settings")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 160, 351, 31))
        font = QtGui.QFont()
        font.setFamily("TT Trailers Trial")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setCursor(QtGui.QCursor(QtCore.Qt.SizeHorCursor))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"background:none;")
        self.label_4.setScaledContents(True)
        self.label_4.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, -80, 330, 330))
        self.label_5.setStyleSheet("background: none;")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("texture/logo.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setWordWrap(False)
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LAST.ai"))
        self.label.setText(_translate("MainWindow", "beta-v-0.0.1-design"))
        self.label_2.setText(_translate("MainWindow", "Если вы ещё этого не сделали."))
        self.label_3.setText(_translate("MainWindow", "Просьба ознакомиться с настройками ассистента!"))
        self.label_4.setText(_translate("MainWindow", "Ответ:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
