# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 500)
        MainWindow.setMinimumSize(QtCore.QSize(400, 500))
        MainWindow.setMaximumSize(QtCore.QSize(400, 500))
        font = QtGui.QFont()
        font.setKerning(False)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../texture/icontitle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: \'#121212\';")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title_text_2 = QtWidgets.QLabel(self.centralwidget)
        self.title_text_2.setGeometry(QtCore.QRect(90, 10, 221, 61))
        font = QtGui.QFont()
        font.setFamily("Unbounded")
        font.setPointSize(32)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.title_text_2.setFont(font)
        self.title_text_2.setMouseTracking(False)
        self.title_text_2.setTabletTracking(False)
        self.title_text_2.setAcceptDrops(False)
        self.title_text_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background:none;")
        self.title_text_2.setOpenExternalLinks(False)
        self.title_text_2.setObjectName("title_text_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setEnabled(True)
        self.pushButton.setGeometry(QtCore.QRect(10, 430, 381, 61))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    display: inline-block !important;\n"
"    family: \'Unbounded Light\' !important;\n"
"    /*text-decoration: none !important;*/\n"
"    background-color: #121212 !important;\n"
"    color: #ffffff !important;\n"
"    border: 5px solid #ffffff !important;\n"
"    border-radius: 24px !important;\n"
"    font-size: 29px !important;\n"
"    padding: 0px 0px !important; \n"
"    transition: all 0.8s ease !important;\n"
"}\n"
"QPushButton:hover{\n"
"    /*text-decoration: none !important; */\n"
"    background-color: #ffffff !important;\n"
"    family: \'Unbounded Light\' !important;\n"
"    color: #121212 !important;\n"
"    border-color: #121212 !important;\n"
"}")
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(10, 80, 381, 341))
        self.tabWidget.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Unbounded Light")
        font.setPointSize(9)
        font.setKerning(True)
        self.tabWidget.setFont(font)
        self.tabWidget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tabWidget.setAcceptDrops(False)
        self.tabWidget.setToolTipDuration(-1)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("\n"
"\n"
"QTabWidget::pane {\n"
"  border: 1px solid white;\n"
"  top:-1px; \n"
"  background: rgb(245, 245, 245);\n"
"\n"
"} \n"
"\n"
"QTabBar::tab {\n"
"  background: rgb(234, 234, 234); \n"
"  border: 1px solid white; \n"
"  padding: 8px;\n"
"  border-radius: 16px;\n"
"\n"
"} \n"
"\n"
"QTabBar::tab:selected { \n"
"  background: white; \n"
"  margin-bottom: -5px; \n"
"  border-radius: 2px\n"
"}")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.title_text_4 = QtWidgets.QLabel(self.tab)
        self.title_text_4.setGeometry(QtCore.QRect(140, 0, 111, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title_text_4.setFont(font)
        self.title_text_4.setMouseTracking(False)
        self.title_text_4.setTabletTracking(False)
        self.title_text_4.setAcceptDrops(False)
        self.title_text_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"background:none;")
        self.title_text_4.setOpenExternalLinks(False)
        self.title_text_4.setObjectName("title_text_4")
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(20, 40, 341, 41))
        self.comboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.tabWidget.addTab(self.tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_3.setGeometry(QtCore.QRect(330, 40, 31, 41))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"border:4px;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.title_text_9 = QtWidgets.QLabel(self.tab_4)
        self.title_text_9.setGeometry(QtCore.QRect(100, 90, 171, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.title_text_9.setFont(font)
        self.title_text_9.setMouseTracking(True)
        self.title_text_9.setTabletTracking(False)
        self.title_text_9.setAcceptDrops(False)
        self.title_text_9.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.title_text_9.setOpenExternalLinks(True)
        self.title_text_9.setObjectName("title_text_9")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_5.setEnabled(False)
        self.lineEdit_5.setGeometry(QtCore.QRect(20, 40, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.lineEdit_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit_5.setInputMask("")
        self.lineEdit_5.setFrame(True)
        self.lineEdit_5.setDragEnabled(False)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.radioButton = QtWidgets.QRadioButton(self.tab_4)
        self.radioButton.setGeometry(QtCore.QRect(10, 10, 301, 21))
        self.radioButton.setStyleSheet("color: rgb(255, 255, 255);")
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.tab_4)
        self.radioButton_2.setGeometry(QtCore.QRect(10, 120, 301, 21))
        self.radioButton_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.radioButton_2.setObjectName("radioButton_2")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_2.setGeometry(QtCore.QRect(20, 40, 341, 41))
        self.comboBox_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.title_text_7 = QtWidgets.QLabel(self.tab_2)
        self.title_text_7.setGeometry(QtCore.QRect(150, 10, 91, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title_text_7.setFont(font)
        self.title_text_7.setMouseTracking(False)
        self.title_text_7.setTabletTracking(False)
        self.title_text_7.setAcceptDrops(False)
        self.title_text_7.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"background:none;\n"
"")
        self.title_text_7.setOpenExternalLinks(False)
        self.title_text_7.setObjectName("title_text_7")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.title_text_8 = QtWidgets.QLabel(self.tab_3)
        self.title_text_8.setGeometry(QtCore.QRect(100, 20, 181, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title_text_8.setFont(font)
        self.title_text_8.setMouseTracking(False)
        self.title_text_8.setTabletTracking(False)
        self.title_text_8.setAcceptDrops(False)
        self.title_text_8.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"background:none;")
        self.title_text_8.setOpenExternalLinks(False)
        self.title_text_8.setObjectName("title_text_8")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_3.setEnabled(True)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 50, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.lineEdit_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_3.setInputMask("")
        self.lineEdit_3.setFrame(True)
        self.lineEdit_3.setDragEnabled(False)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.listWidget = QtWidgets.QListWidget(self.tab_5)
        self.listWidget.setGeometry(QtCore.QRect(10, 50, 361, 192))
        self.listWidget.setStyleSheet("QListWidget {\n"
"    color: white;\n"
"\n"
"}")
        self.listWidget.setObjectName("listWidget")
        self.title_text_10 = QtWidgets.QLabel(self.tab_5)
        self.title_text_10.setGeometry(QtCore.QRect(150, 20, 101, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title_text_10.setFont(font)
        self.title_text_10.setMouseTracking(False)
        self.title_text_10.setTabletTracking(False)
        self.title_text_10.setAcceptDrops(False)
        self.title_text_10.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"background:none;")
        self.title_text_10.setOpenExternalLinks(False)
        self.title_text_10.setObjectName("title_text_10")
        self.tabWidget.addTab(self.tab_5, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LAST.settings"))
        self.title_text_2.setText(_translate("MainWindow", "settings"))
        self.pushButton.setText(_translate("MainWindow", "Применить"))
        self.title_text_4.setText(_translate("MainWindow", "Микрофон"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Ассистент"))
        self.pushButton_3.setText(_translate("MainWindow", "..."))
        self.title_text_9.setText(_translate("MainWindow", "<a href=\'https://alphacephei.com/vosk/models\'>Ссылка на сайт с моделями</a>"))
        self.lineEdit_5.setText(_translate("MainWindow", "C:/VASKILL/models/small_model_ru"))
        self.radioButton.setText(_translate("MainWindow", "Kaldi(vosk)"))
        self.radioButton_2.setText(_translate("MainWindow", "Google Speech Recognition"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Распознаватель"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Dark"))
        #self.comboBox_2.setItemText(1, _translate("MainWindow", "Light"))
        self.title_text_7.setText(_translate("MainWindow", "       тема"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Тема"))
        self.title_text_8.setText(_translate("MainWindow", "Выберите имя для ассистента"))
        self.lineEdit_3.setText(_translate("MainWindow", "SkillBot"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Косметика ассистента"))
        self.title_text_10.setText(_translate("MainWindow", "Модификации"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Моды"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
